# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
            ],
            managers=[
                ('meetings', django.db.models.manager.Manager()),
            ],
        ),
    ]
