# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(default='Dresden', max_length=100)),
                ('postcode', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterModelManagers(
            name='meeting',
            managers=[
            ],
        ),
    ]
