# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20161019_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='meeting.Location'),
            preserve_default=False,
        ),
    ]
