# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meeting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
